[advisories]
version = 2
vulnerabilities = "deny"
unsound = "deny"
unmaintained = "warn"
yanked = "warn"
ignore = ["RUSTSEC-2024-0445"]

[licenses]
version = 2
unlicensed = "deny"
copyleft = "warn"
default = "allow"
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "ISC",
  "Unicode-DFS-2016"
]

[bans]
version = 2
multiple-versions = "warn"
wildcards = "deny"
